apiVersion: v1
kind: PersistentVolume
metadata:
  name: kannon-cache-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kannon-cache-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
