---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-manager
  namespace: kannon-quick-starter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager-role
  namespace: kannon-quick-starter
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-rolebinding
  namespace: kannon-quick-starter
subjects:
- kind: ServiceAccount
  name: job-manager
  namespace: kannon-quick-starter
roleRef:
  kind: Role
  name: job-manager-role
  apiGroup: rbac.authorization.k8s.io
