apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
  namespace: kannon-quick-starter
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /cache
      name: kannon-cache
  volumes:
  - name: kannon-cache
    persistentVolumeClaim:
      claimName: kannon-cache-claim
  restartPolicy: Never
