name: Lint

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Run mypy, yapf, isort, and flake8
        run: |
          poetry run tox -e mypy,yapf,isort,flake8
