name: Publish

on:
  push:
    tags: '*'

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry poetry-dynamic-versioning twine
    - name: Build
      run: |
        poetry build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
